"""Build both supported GitHub Pages roots from one source. No dependencies."""
import json, html, pathlib, shutil
ROOT=pathlib.Path(__file__).resolve().parents[1]
esc=html.escape
entries=sorted([e for e in json.loads((ROOT/'content/journals.json').read_text()) if e.get('published')],key=lambda e:e['number'])
site=json.loads((ROOT/'content/site.json').read_text())
assert entries and len({e['number'] for e in entries})==len(entries)
latest=entries[-1]
def url(e,p=''): return f"{p}journal/entry-{e['number']:02d}.html"
def flourish(p=''): return f'<img class="flourish" src="{p}assets/flourish.svg" alt="" width="440" height="48">'
def shell(body,title='The Grimsby Institute',p='',kind='home',description='The ongoing H-31 inquiry. Read the journals of Dr. Elias Grimsby, somewhere beyond Vaguely England.'):
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#242821"><title>{esc(title)}</title><meta name="description" content="{esc(description)}"><meta property="og:title" content="{esc(title)}"><meta property="og:description" content="{esc(description)}"><meta property="og:image" content="https://collective001.github.io/GrimsbyInstitute/assets/institute-engraving.png"><link rel="icon" href="{p}assets/crest.svg" type="image/svg+xml"><script>try {{ if (sessionStorage.getItem('grimsby-entered') !== 'yes') document.documentElement.classList.add('entrance-pending'); }} catch (_) {{ document.documentElement.classList.add('entrance-pending'); }}</script><link rel="stylesheet" href="{p}styles.css?v=entrance-1"><script src="{p}site.js?v=entrance-1" defer></script></head><body class="{kind}-page"><a class="skip" href="#main">Skip to content</a><div class="entrance-screen" role="dialog" aria-modal="true" aria-labelledby="entrance-title" tabindex="-1"><div class="folio entrance-paper"><img class="entrance-crest" src="{p}assets/crest.svg" alt="Institute crest: Baryon and a rat" width="80" height="83"><p class="entrance-name">The Grimsby Institute</p>{invitation(p, entrance=True)}</div></div><div class="folio site-folio"><img class="seasonal" src="{p}assets/autumn.svg" alt="" width="420" height="300"><img class="seasonal right" src="{p}assets/autumn.svg" alt="" width="420" height="300"><header class="masthead"><a href="{p}index.html" aria-label="The Grimsby Institute home"><img class="crest" src="{p}assets/crest.svg" alt="Institute crest: Baryon and a rat" width="240" height="250"></a><p class="overline">An establishment for the advancement of questionable findings</p><h1><a href="{p}index.html">The Grimsby Institute</a></h1><p class="submast">Experimental Medicine &amp; Unfinished Inquiries</p><div class="edition"><span>Vaguely England</span><span>Official institutional record</span><span>Autumn Edition · H-31</span></div><nav class="main-nav" aria-label="Main navigation"><a href="{p}index.html#case">The H-31 Inquiry</a><a href="{p}archive.html" {'aria-current="page"' if kind=='archive' else ''}>The Journals</a><a href="{p}index.html#expedition">The Expedition</a><a href="{p}index.html#invitation" data-open-invitation>Invitation</a></nav></header><main id="main" tabindex="-1">{body}</main><footer><p>The Grimsby Institute · Vaguely England</p><p>Further study is required.</p><p class="aside">Seasonal embellishments do not constitute a change in research priorities.</p></footer></div></body></html>'''
def index_list(p=''):
    return '<ol class="index-list">'+''.join(f'<li><a href="{url(e,p)}"><span class="index-roman">{e["roman"]}</span><span><span class="index-title">{esc(e["title"])}</span><span class="index-date">{esc(e["date"])}</span></span><span class="index-arrow" aria-hidden="true">↗</span></a></li>' for e in entries)+'</ol>'
map_svg=(ROOT/'assets/route-map.svg').read_text()
rsvp=f'<a class="button" href="{esc(site["rsvpUrl"],quote=True)}" target="_blank" rel="noopener noreferrer">Confirm Your Attendance</a>' if site.get('rsvpUrl') else '<p class="small">Kindly confirm attendance with your host.<br>Please include your party size and any dietary requirements.</p>'
def invitation(p='', entrance=False):
    prefix='entrance' if entrance else 'invitation'
    content=f'''<section class="invitation" id="{prefix}" aria-labelledby="{prefix}-title"><p class="eyebrow">An autumn notice to invited guests</p>{flourish(p)}<h2 id="{prefix}-title">Your presence is requested.</h2><p class="party-date">October 24, 2026 · Seven in the Evening</p><p>Covington, Kentucky</p><p class="small">Costumes are not necessary.<br>The precise address will be provided privately.</p>{rsvp}<p class="eyebrow" style="margin-top:25px">Upon arrival, the phrase is</p><p class="admission">“Today belongs to the rat.”</p>{flourish(p)}</section>'''
    if entrance:
        content=content.replace('</section>', '<div class="entrance-actions"><button class="button entrance-enter" type="button">ENTER THE INSTITUTE</button></div></section>')
    return content
home=f'''<section class="home-opening" id="case"><div class="case-notice"><p class="eyebrow">Notice of an ongoing inquiry</p><h2>Subject H-31</h2><p class="subtitle">Whereabouts presently unconfirmed.</p>{flourish()}<span class="status">{esc(site['status']).upper()}</span><p>A promising experiment.<br>An unsecured enclosure.<br>A regrettable loss of breakfast.</p><p>Dr. Elias Grimsby’s pursuit is recorded herein.<br>The investigation remains ongoing.</p><div class="actions"><a class="button" href="{url(entries[0])}">Begin with Entry I</a><a class="button secondary" href="{url(latest)}">Latest Dispatch ↗</a></div></div><figure class="establishment"><img src="assets/institute-engraving.png" alt="An intricate engraving of the Institute, with autumn foliage, black drapery, and small pumpkins at its iron gates." width="1536" height="1024" fetchpriority="high"><figcaption class="plate-caption">Plate I. The Institute &amp; its surrounding uncertainties.</figcaption><p class="handnote">The window has since been brought to our attention.</p></figure></section>
<section class="dispatch-strip" aria-labelledby="latest-title"><div class="eyebrow">Latest correspondence<br>Entry {latest['roman']}</div><div><h2 id="latest-title"><a href="{url(latest)}">{esc(latest['title'])}</a></h2><p>{esc(latest['date'])} · {esc(site['latestLocation'])}</p></div><a href="{url(latest)}" class="entry-no" aria-label="Read latest dispatch">↗</a></section>
<section aria-labelledby="particulars"><div class="section-head"><div><p class="eyebrow">Case register / H-31</p><h2 id="particulars">The known particulars.</h2></div></div><div class="case-details"><div><figure class="portrait"><span class="question" aria-hidden="true">?</span><p>A satisfactory likeness<br>has yet to be obtained.</p></figure></div><div><dl class="ledger"><div><dt>Subject designation</dt><dd>H-31, referred to as “Gary”</dd></div><div><dt>Last reported sighting</dt><dd>{esc(site['lastSighting'])}</dd></div><div><dt>Reliable inducement</dt><dd>Reese confections</dd></div><div><dt>Attending researcher</dt><dd>Dr. Elias Grimsby</dd></div></dl></div><div><figure class="evidence"><img src="assets/evidence.svg" alt="Scientific illustration of a discarded Reese confection wrapper" width="360" height="220"><figcaption><span class="eyebrow">Material evidence</span><br>One discarded confection wrapper.<small>Recovered along the subject’s trail.<br>See Entry VI.</small></figcaption></figure></div></div></section>
<section id="expedition" aria-labelledby="expedition-title"><div class="section-head"><div><p class="eyebrow">Field chart / The pursuit</p><h2 id="expedition-title">Beyond the Institute.</h2></div></div><div class="map-sheet">{map_svg}<div class="map-caption"><span>Solid line: Grimsby’s documented passage, now reaching Maine.<br>Crossed circle: reported H-31 sighting. The subject remains unlocated.</span><button class="replay" type="button">Retrace the passage ↻</button></div></div><p class="handnote">Current circumstances: {esc(site['doctorLocation'])}.</p></section>
<section id="journals" aria-labelledby="journals-title"><div class="section-head"><div><p class="eyebrow">The record, thus far</p><h2 id="journals-title">A most necessary paper trail.</h2></div><a href="archive.html">Open the archive ↗</a></div>{index_list()}<p class="institute-note">Further dispatches will be added as they reach the Institute.<br>The chronology is maintained by entry number. The dates are Dr. Grimsby’s responsibility.</p></section>
{invitation()}'''
(ROOT/'index.html').write_text(shell(home))
(ROOT/'archive.html').write_text(shell(f'<header class="archive-intro"><p class="eyebrow">H-31 / Collected correspondence</p><h1>The journals of Elias Grimsby</h1>{flourish()}<p>Research notes, offsite observations, and matters which the doctor considers equally deserving of a written record.</p><p>Read in numbered order. Dates have been preserved as submitted.</p></header>{index_list()}',title='The Journals | The Grimsby Institute',kind='archive'))
for old in (ROOT/'journal').glob('entry-*.html'): old.unlink()
for i,e in enumerate(entries):
    paragraphs=[]
    for para in e['text'].split('\n\n'):
        if para.startswith('- '): paragraphs.append('<ul>'+''.join('<li>'+esc(line[2:])+'</li>' for line in para.splitlines())+'</ul>')
        else: paragraphs.append('<p>'+esc(para)+'</p>')
    prev=f'<a href="entry-{entries[i-1]["number"]:02d}.html">← Entry {entries[i-1]["roman"]}</a>' if i else '<a href="../archive.html">← The Archive</a>'
    nxt=f'<a href="entry-{entries[i+1]["number"]:02d}.html">Entry {entries[i+1]["roman"]} →</a>' if i+1<len(entries) else '<span>Further correspondence awaited.</span>'
    signature=esc(e['signature']).replace('Elias Grimsby','<span class="name">Elias Grimsby</span>')
    body=f'''<div class="journal-top"><a href="../archive.html">← All journal entries</a><span>H-31 / Entry {e['roman']}</span></div><div class="journal-layout"><aside class="marginalia" aria-label="Archive reference"><span>JOURNAL LEAF</span><span class="big-roman">{e['roman']}</span><span>H-31<br>Institutional copy</span></aside><article class="journal-paper"><header class="journal-heading"><p class="entry-label">Entry {e['roman']}</p><h1>{esc(e['heading'])}</h1><p class="strange-date">{esc(e['date'])}</p>{flourish('../')}</header><div class="journal-text">{''.join(paragraphs)}</div><div class="signature">{signature}</div><nav class="journal-navigation" aria-label="Journal pagination">{prev}{nxt}</nav></article><aside class="marginalia" aria-label="Editorial note"><span>FILED AS RECEIVED</span><span>The doctor’s wording is retained.</span></aside></div>'''
    (ROOT/'journal'/f'entry-{e["number"]:02d}.html').write_text(shell(body,title=f'Entry {e["roman"]}: {e["title"]} | The Grimsby Institute',p='../',kind='reading',description=e['text'].split('\n')[0]))
# GitHub Pages may publish from /docs or repository root. Both use the same output.
DOCS=ROOT/'docs'
if DOCS.exists(): shutil.rmtree(DOCS)
DOCS.mkdir()
for filename in ['index.html','archive.html','styles.css','site.js','.nojekyll']:
    shutil.copy2(ROOT/filename,DOCS/filename)
for dirname in ['assets','journal']: shutil.copytree(ROOT/dirname,DOCS/dirname)
print(f'Built homepage, archive, and {len(entries)} journal pages into root and docs/.')
